# Generated by Django 3.1 on 2020-08-15 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Naver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('birthdate', models.DateField(verbose_name='Data de Nascimento')),
                ('admission_date', models.DateField(verbose_name='Data de Admissão')),
                ('job_role', models.CharField(max_length=100, verbose_name='Cargo')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naver', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Naver',
                'verbose_name_plural': 'Navers',
            },
        ),
        migrations.CreateModel(
            name='NaverProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.naver', verbose_name='Naver')),
            ],
            options={
                'verbose_name': 'Navers-Projects',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('navers', models.ManyToManyField(through='app.NaverProject', to='app.Naver', verbose_name='Navers')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='naverproject',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.project', verbose_name='Project'),
        ),
    ]
