# Generated by Django 3.1 on 2020-08-15 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='navers',
            field=models.ManyToManyField(related_name='projects', through='app.NaverProject', to='app.Naver', verbose_name='Navers'),
        ),
    ]
